
# カーソル移動時にアニメーション視覚効果
[[plugins]]
repo = 'edluffy/specs.nvim'
on_event = 'VimEnter'
lua_source = '''
require('specs').setup{
    show_jumps  = true,
    min_jump = 5,
    popup = {
        delay_ms = 0, -- delay before popup displays
        inc_ms = 2, -- time increments used for fade/resize effects
        blend = 10, -- starting blend, between 0-100 (fully transparent), see :h winblend
        width = 1000,
        winhl = "PMenuSel",
        fader = require('specs').linear_fader,
        resizer = require('specs').empty_resizer
    },
    ignore_filetypes = {},
    ignore_buftypes = {
        nofile = true,
    },
}
'''
