# disabled

[[plugins]]
repo = 'akinsho/bufferline.nvim'
on_event = 'VimEnter'
lua_source = '''
local bufferline = require('bufferline')
bufferline.setup({
  options = {
    style_preset = bufferline.style_preset.no_italic,
    -- or you can combine these e.g.
    style_preset = {
        bufferline.style_preset.no_italic,
        bufferline.style_preset.no_bold
    },
    show_buffer_close_icons = false,
    show_close_icon = false,
  },
})
'''
lua_add = '''
vim.api.nvim_create_user_command(
  'BufferLineCloseCurrent',
  function(opts)
    -- TODO: create new empty buffer if only have one managed buffer
    vim.api.nvim_command('bd')
    vim.api.nvim_command('BufferLineGoToBuffer 1')
  end,
  {}
)
-- vim.keymap.set('n', '<C-x><C-c>', '<Cmd>BufferLineCloseCurrent<CR>')
vim.keymap.set('n', '<Space>q', '<Cmd>BufferLineCloseCurrent<CR>')
'''
