
[[plugins]]
repo = 'famiu/bufdelete.nvim'
on_event = 'VimEnter'
on_cmd = 'Bdelete'
lua_source = '''
require('bufdelete').bufdelete(0, true)
'''

lua_add = '''
vim.api.nvim_create_user_command(
  'Bdelete',
  function(opts)
    require('bufdelete').bufdelete(0, true)
  end,
  {}
)
vim.keymap.set('n', '<C-x><C-c>', '<Cmd>Bdelete<CR>')
vim.keymap.set('n', '<Space>q', '<Cmd>Bdelete<CR>')
'''
