# nolazy

[[plugins]]
repo = 'projekt0n/github-nvim-theme'
lua_add = '''
vim.o.background = 'dark'
vim.cmd('colorscheme github_dark_dimmed')
'''

[[plugins]]
repo = 'folke/tokyonight.nvim'
lua_add = '''
vim.o.background = 'dark'
--vim.o.background = 'light'
require('tokyonight').setup({
  style = 'night',
  light_style = 'day',
  --transparent = false,
  --terminal_colors = true,
  styles = {
    sidebars = 'dark',
    floats = 'dark',
  },
  sidebars = { 'fern', 'terminal' },
})
--vim.cmd('colorscheme tokyonight')
'''

[[plugins]]
repo = 'Mofiqul/vscode.nvim'
lua_add = '''
--vim.o.background = 'dark'

local c = require('vscode.colors').get_colors()
require('vscode').setup({
    style = 'dark',
    -- transparent = true,
    italic_comments = true,
    disable_nvimtree_bg = true,
    -- Override colors (see ./lua/vscode/colors.lua)
    --color_overrides = {
      -- vscLineNumber = '#FFFFFF',
    --},

    -- Override highlight groups (see ./lua/vscode/theme.lua)
    group_overrides = {
    -- this supports the same val table as vim.api.nvim_set_hl
      -- use colors from this colorscheme by requiring vscode.colors!
      Cursor = {
        fg=c.vscDarkBlue,
        bg=c.vscLightGreen,
        bold=true
      },
    }
})
-- require('vscode').load()
'''
