# nolazy

[[plugins]]
repo = 'kana/vim-submode'

[[plugins]]
repo = 'Shougo/context_filetype.vim'
hook_add = '''
let g:context_filetype#filetypes = context_filetype#default_filetypes()
'''

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = 'context_filetype.vim'

[[plugins]]
repo = 'mattn/vim-findroot'
hook_add = '''
let g:findroot_patterns = [
  \  '.git/',
  \  '.gitignore',
  \  'pyproject.toml',
  \  'package.json',
  \  'manifest.json',
  \  '*.csproj',
  \  '*.sln',
  \  'Rakefile',
  \  'Gemfile',
  \  'Gemfile.lock',
  \  '.tool-versions',
  \  'init.vim',
  \]
'''

[[plugins]]
repo = 'osyo-manga/vim-over'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'osyo-manga/vim-automatic'
hook_add = '''
let g:automatic_config = []
"let g:automatic_config = [
"      \ #{
"      \   match: #{
"      \     filetype: 'help',
"      \     buftype: 'help',
"      \   },
"      \   set: #{
"      \     move: 'bottom',
"      \     height: '80%',
"      \     is_close_focus_out: 1,
"      \   }
"      \ }
"\ ]
'''

[[plugins]]
repo = 'lambdalisue/kensaku.vim'
depends = 'denops.vim'

