# nolazy

[[plugins]]
repo = 'Shougo/context_filetype.vim'
hook_add = '''
let g:context_filetype#filetypes = context_filetype#default_filetypes()
'''

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = 'context_filetype.vim'

[[plugins]]
repo = 'mattn/vim-findroot'
hook_add = '''
let g:findroot_patterns = [
  \  '.git/',
  \  '.gitignore',
  \  'pyproject.toml',
  \  'package.json',
  \  'manifest.json',
  \  '*.csproj',
  \  '*.sln',
  \  'Rakefile',
  \  'Gemfile',
  \  'Gemfile.lock',
  \  '.tool-versions',
  \  'init.vim',
  \]
'''

[[plugins]]
repo = 'osyo-manga/vim-over'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'osyo-manga/vim-automatic'
hook_add = '''
let g:automatic_config = []
let g:automatic_config = [
      \ #{
      \   match: #{
      \     buftype: 'terminal',
      \   },
      \   set: #{
      \     move: 'bottom',
      \     height: '40%',
      \     is_close_focus_out: 1,
      \   }
      \ }
\ ]
'''

[[plugins]]
repo = 'lambdalisue/kensaku.vim'
depends = 'denops.vim'

[[plugins]]
repo = 'lukas-reineke/indent-blankline.nvim'
lua_add = '''

-- local highlight = {
--     "RainbowRed",
--     "RainbowYellow",
--     "RainbowBlue",
--     "RainbowOrange",
--     "RainbowGreen",
--     "RainbowViolet",
--     "RainbowCyan",
-- }

-- local hooks = require "ibl.hooks"

-- create the highlight groups in the highlight setup hook, so they are reset
-- every time the colorscheme changes

-- hooks.register(hooks.type.HIGHLIGHT_SETUP, function()
--     vim.api.nvim_set_hl(0, "RainbowRed", { fg = "#E06C75" })
--     vim.api.nvim_set_hl(0, "RainbowYellow", { fg = "#E5C07B" })
--     vim.api.nvim_set_hl(0, "RainbowBlue", { fg = "#61AFEF" })
--     vim.api.nvim_set_hl(0, "RainbowOrange", { fg = "#D19A66" })
--     vim.api.nvim_set_hl(0, "RainbowGreen", { fg = "#98C379" })
--     vim.api.nvim_set_hl(0, "RainbowViolet", { fg = "#C678DD" })
--     vim.api.nvim_set_hl(0, "RainbowCyan", { fg = "#56B6C2" })
-- end)

require("ibl").setup {
  indent = {
    char = '▏',
    --char = '',
    --highlight = highlight
  },
  whitespace = {
    -- highlight = highlight,
    remove_blankline_trail = false,
  },
  scope = {
    enabled = true
  }
}
'''

[[plugins]]
repo = 'norcalli/nvim-colorizer.lua'
lua_add = '''
require("colorizer").setup()
'''
