[[plugins]]
repo = 'folke/edgy.nvim'
on_event = 'VimEnter'
lua_source = '''
local bottom = {
  {
    ft = 'ugaterm',
    title = 'Terminal',
    open = 'UgatermOpen',
    pinned = true,
  },
--  {
--    ft = 'ddu-ff',
--    title = 'Diagnostics',
--    open = 'Ddu -name=edgy:lsp:diagnostics',
--    filter = function(buf)
--      return vim.b[buf].ddu_ui_name == 'edgy:lsp:diagnostics'
--    end,
--    pinned = true,
--  },
--  {
--    ft = 'quickrun',
--    title = 'QuickRun',
--  },
}
local left = {
  {
    ft = 'fern',
    size = { height = 0.5 },
    title = 'Files',
    open = 'Fern . -drawer -keep -reveal=%',
    pinned = true,
  },
}
local right = {
  {
    ft = 'ddu-ff',
    size = { height = 0.5 },
    title = 'Symbols',
    open = 'Ddu -name=edgy:lsp:documentSymbol',
    filter = function(buf)
      return vim.b[buf].ddu_ui_name == 'edgy:lsp:documentSymbol'
    end,
    pinned = true,
  },
}
local top = {}
require('edgy').setup({
  top = top,
  bottom = bottom,
  left = left,
  right = right,

  options = {
    left = { size = 40 },
    right = { size = 40 },
    bottom = { size = 20 },
  },

  exit_when_last = true,
  close_when_all_hidden = false,
  animate = {
    enabled = false,
  },
})
'''
lua_add = '''
-- views can only be fully collapsed with the global statusline
vim.opt.laststatus = 3
-- Default splitting will cause your main splits to jump when opening an edgebar.
-- To prevent this, set `splitkeep` to either `screen` or `topline`.
vim.opt.splitkeep = "screen"

vim.api.nvim_create_user_command(
  'ToggleSidebar',
  function(opts)
    require('edgy').toggle('left')
  end,
  {}
)
vim.api.nvim_create_user_command(
  'ToggleSecondarySidebar',
  function(opts)
    require('edgy').toggle('right')
  end,
  {}
)
vim.api.nvim_create_user_command(
  'ToggleBottomPane',
  function(opts)
    require('edgy').toggle('bottom')
  end,
  {}
)
vim.api.nvim_create_user_command(
  'GoToEditorPane',
  function(opts)
    require('edgy').goto_main()
  end,
  {}
)

'''
hook_add = '''
nnoremap <Space>s :ToggleSidebar<CR>
nnoremap <Space>r :ToggleSecondarySidebar<CR>
nnoremap <Space>b :ToggleBottomPane<CR>
nnoremap <Space>m :GoToEditorPane<CR>
'''
