
[[plugins]]
repo = 'lambdalisue/fern.vim'
on_cmd = 'Fern'
hook_add = '''
nnoremap <Space>s :Fern . -drawer -toggle -reveal=% -width=30<CR>
augroup MyFern
  autocmd FileType fern setlocal nonumber
augroup END
'''

[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'
depends = 'fern.vim'
on_source = 'fern.vim'

[[plugins]]
repo = 'lambdalisue/fern-mapping-git.vim'
depends = 'fern.vim'
on_source = 'fern.vim'

[[plugins]]
repo = 'lambdalisue/nerdfont.vim'
on_source = 'fern-renderer-nerdfont.vim'

[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'
depends = ['fern.vim', 'nerdfont.vim']
on_source = 'fern.vim'
hook_add = '''
let g:fern#renderer = "nerdfont"
'''

[[plugins]]
repo = 'lambdalisue/fern-bookmark.vim'
depends = 'fern.vim'
on_source = 'fern.vim'
