
[[plugins]]
repo = 'lambdalisue/gin.vim'
on_cmd = [
  'Gin',
  'GinBuffer',
  'GinBranch',
  'GinBrowse',
  'GinCd',
  'GinLcd',
  'GinTcd',
  'GinChaperon',
  'GinDiff',
  'GinEdit',
  'GinLog',
  'GinPatch',
  'GinStatus'
]

[[plugins]]
repo = 'lewis6991/gitsigns.nvim'
on_event = 'VimEnter'
lua_source = '''
require('gitsigns').setup()
'''
