[[plugins]]
repo = 'kana/vim-submode'
on_event = 'VimEnter'
hook_source = '''
let g:submode_keep_leaving_key = 1
call submode#enter_with('changetab', 'n', '', 'gt', '<Cmd>BufferLineCycleNext<CR>')
call submode#enter_with('changetab', 'n', '', 'gT', '<Cmd>BufferLineCyclePrev<CR>')
call submode#map('changetab', 'n', '', 't', '<Cmd>BufferLineCycleNext<CR>')
call submode#map('changetab', 'n', '', 'T', '<Cmd>BufferLineCyclePrev<CR>')
'''
