
[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
if = '!has("win32")'
on_event = ['BufRead', 'CursorHold']
hook_post_update = 'TSUpdate'
lua_source = '''
require('nvim-treesitter.configs').setup {
  ensure_installed = 'all',
  additional_vim_regex_highlighting = false,
  highlight = {
    enable = true,
    disable = {
      'toml',
      'lua',
    }
  },
}
'''

[[plugins]]
repo = 'virchau13/tree-sitter-astro'
on_ft = 'astro'
hook_add = '''
autocmd BufRead,BufEnter *.astro set filetype=astro
'''
